# -*- coding: utf-8 -*-
"""黄金投资AI决策雷达主程序

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d8vVoPuxgkZlQtSVNy5D7Jb-Y2TxLUVp
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import feedparser
from datetime import datetime

# --- Page Configuration ---
st.set_page_config(page_title="黄金投资 AI 决策室", page_icon="🏆", layout="wide")

# --- Core Logic: Data Retrieval (Cache 1 hour for hourly updates) ---
@st.cache_data(ttl=3600)
def get_financial_data():
    """Fetches key financial data (Gold, DXY, VIX, TNX) on a 1-hour interval for 1 month."""
    # Define assets to monitor
    tickers = {
        '黄金 (Gold)': 'GC=F',
        '美元指数 (DXY)': 'DX-Y.NYB',
        '10年美债收益率': '^TNX',
        '恐慌指数 (VIX)': '^VIX', # Geopolitical risk proxy
        '标普500': '^GSPC'
    }

    data_store = {}

    # Download 1-month data with 1-hour intervals
    for name, symbol in tickers.items():
        try:
            # Use pre/post market data if available for continuous charting
            df = yf.download(symbol, period="1mo", interval="1h", progress=False, prepost=True)
            if not df.empty:
                data_store[name] = df
        except Exception as e:
            # Log the error but don't stop the app
            print(f"Failed to fetch {name} ({symbol}): {e}")

    return data_store

# --- Core Logic: News Scraping (Political/Macro) ---
# **重要更新：将缓存时间缩短至 5 分钟 (300秒) 以实现更快的量化新闻刷新**
@st.cache_data(ttl=300)
def get_news():
    """Fetches recent financial news from RSS feeds."""
    rss_urls = [
        "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10000664", # CNBC Finance
        "https://feeds.content.dowjones.io/public/rss/mw_topstories" # Market Watch Top Stories
    ]
    news_items = []

    for url in rss_urls:
        try:
            feed = feedparser.parse(url)
            # Take the top 5 entries from each source
            for entry in feed.entries[:5]:
                # Convert time format if possible
                published_time = entry.get('published', '刚刚')
                try:
                    # Attempt to parse common RSS date formats
                    # Note: The format string needs to handle the RSS timezone offset if present
                    dt = datetime.strptime(published_time, '%a, %d %b %Y %H:%M:%S %z')
                    published_time = dt.strftime('%Y-%m-%d %H:%M')
                except:
                    pass # Keep '刚刚' or original string if parsing fails

                news_items.append({
                    'title': entry.title,
                    'link': entry.link,
                    'published': published_time
                })
        except Exception as e:
             print(f"Failed to fetch RSS from {url}: {e}")

    return news_items

# --- Core Logic: AI Scoring System with Robustness ---
def calculate_signal(data):
    """Calculates a numerical score and reasons based on financial data."""
    score = 0
    reasons = []

    # --- 1. Gold Technical Analysis (MA & RSI) ---
    gold_df = data.get('黄金 (Gold)')
    if gold_df is not None and not gold_df.empty:
        # Use .item() to ensure a scalar value is extracted, preventing "ambiguous" error
        current_price = gold_df['Close'].iloc[-1].item()
        gold_series = gold_df['Close']

        # 1.1 Moving Average (MA) Calculation with Fallback
        required_ma_points = 50
        fallback_period = 10

        if len(gold_series) >= required_ma_points:
            # Use .item() to ensure a scalar value
            ma_value = gold_series.rolling(required_ma_points).mean().iloc[-1].item()
            ma_period = required_ma_points
        elif len(gold_series) >= fallback_period:
            # Use .item() to ensure a scalar value
            ma_value = gold_series.rolling(fallback_period).mean().iloc[-1].item()
            ma_period = fallback_period
            reasons.append(f"⚠️ 均线容错：数据不足 {required_ma_points} 小时，使用 {fallback_period} 小时均线计算。")
        else:
            # If even 10 points are not available, skip MA calculation
            ma_value = current_price # Default to current price to avoid division by zero/NaN issues
            ma_period = 0
            reasons.append("🚫 均线跳过：数据点太少，无法计算任何均线。")

        if ma_period > 0:
            if current_price > ma_value:
                score += 2
                reasons.append(f"📈 技术面：金价位于{ma_period}小时均线上方 (看涨)")
            else:
                score -= 2
                reasons.append(f"📉 技术面：金价位于{ma_period}小时均线下方 (看跌)")

        # 1.2 RSI Calculation (14-period) with Fallback
        required_rsi_points = 14
        rsi = None

        if len(gold_series) >= required_rsi_points:
            delta = gold_series.diff()
            gain = (delta.where(delta > 0, 0)).rolling(required_rsi_points).mean()
            loss = (-delta.where(delta < 0, 0)).rolling(required_rsi_points).mean()
            # Avoid division by zero when loss is 0
            rs = gain / loss.replace(0, 1e-10)
            # Use .item() to ensure a scalar value
            rsi = (100 - (100 / (1 + rs))).iloc[-1].item()
        else:
            reasons.append("🚫 RSI跳过：数据点太少，无法计算 RSI (需14小时)。")

        if rsi is not None and not pd.isna(rsi):
            reasons.append(f"🎯 实时RSI (14H): {rsi:.2f}")
            if rsi < 30:
                score += 1
                reasons.append("⚡ RSI指标：进入超卖区间 (反弹概率大)")
            elif rsi > 70:
                score -= 1
                reasons.append("⚠️ RSI指标：进入超买区间 (回调风险大)")

    # --- 2. Macro Analysis (USD & VIX) ---

    # 2.1 USD Index (DXY)
    dxy_df = data.get('美元指数 (DXY)')
    if dxy_df is not None and len(dxy_df) >= 2:
        # Compare current to 24 hours ago (or first available point if less than 24)
        # Use .item() to ensure a scalar value
        dxy_now = dxy_df['Close'].iloc[-1].item()

        # Try to get 24 hours ago, otherwise use the first point as comparison base
        idx_prev = -24 if len(dxy_df) >= 24 else 0
        # Use .item() to ensure a scalar value
        dxy_prev = dxy_df['Close'].iloc[idx_prev].item()

        if dxy_now < dxy_prev:
            score += 2
            reasons.append(f"💵 宏观面：美元指数 ({dxy_now:.2f}) 日内相对走弱 (利好黄金)")
        else:
            score -= 2
            reasons.append(f"💵 宏观面：美元指数 ({dxy_now:.2f}) 日内相对走强 (利空黄金)")

    # 2.2 Volatility Index (VIX - Geopolitical/Fear Proxy)
    vix_df = data.get('恐慌指数 (VIX)')
    if vix_df is not None and not vix_df.empty:
        # Use .item() to ensure a scalar value
        vix_now = vix_df['Close'].iloc[-1].item()
        reasons.append(f"💣 恐慌指数VIX: {vix_now:.2f}")
        if vix_now > 20: # High fear
            score += 2
            reasons.append("💣 情绪面：市场恐慌指数(VIX)较高 (避险资金流入)")
        elif vix_now < 13: # Extreme complacency
            score -= 1
            reasons.append("🕊️ 情绪面：市场极度平静 (避险需求低)")

    return score, reasons

# --- UI Rendering ---
def main():
    st.title("🥇 黄金投资 AI 决策室")

    # Attempt to load data
    try:
        with st.spinner('正在连接全球交易所与新闻源...'):
            data = get_financial_data()
            news = get_news()

            # Check if essential data (Gold) is available
            if '黄金 (Gold)' not in data or data['黄金 (Gold)'].empty:
                st.error("数据源连接失败或市场休市中。请稍后再试或检查市场状态。")
                return

            score, reasons = calculate_signal(data)

            # Note the different refresh rates in the summary
            st.markdown(f"*数据更新时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} (**新闻每 5 分钟刷新**，技术指标每小时刷新)*")

    except Exception as e:
        # Catch unexpected errors during core processing
        st.error(f"系统启动失败: {e}")
        st.stop()
        return

    # --- Sidebar ---
    with st.sidebar:
        st.header("关于系统")
        st.info("本系统每小时抓取美联储利率预期(美债)、全球地缘政治恐慌度(VIX)和美元走势，综合计算买卖信号。")
        st.caption("系统依赖 yfinance 获取数据，可能受市场闭市影响数据量。")
        if st.button("🔄 手动强制刷新数据"):
            st.cache_data.clear()
            st.rerun()

    # --- 1. Core Decision Dashboard ---
    st.divider()
    col1, col2, col3 = st.columns([1, 2, 1])

    gold_df = data['黄金 (Gold)']
    cur_gold = gold_df['Close'].iloc[-1].item()

    # Calculate difference for the metric
    if len(gold_df) >= 2:
        gold_delta = cur_gold - gold_df['Close'].iloc[-2].item()
    else:
        gold_delta = 0 # Not enough data for delta

    with col1:
        st.metric("实时金价 (USD/oz)", f"${cur_gold:.2f}",
                  f"{gold_delta:.2f}")

    with col2:
        # Determine the explicit action based on score
        action = "观望 (HOLD)"
        action_style = st.warning

        if score >= 4:
            action = "强力买入 (STRONG BUY)"
            action_style = st.success

        elif score >= 1:
            action = "逢低买入 (CAUTIOUS BUY)"
            action_style = st.info

        elif score <= -4:
            action = "强力卖出/做空 (STRONG SELL)"
            action_style = st.error

        elif score < 0:
             action = "逢高卖出/做空 (CAUTIOUS SELL)"
             action_style = st.warning

        # Explicit Display
        st.subheader("🤖 AI 实时操作建议")
        action_style(f"👉 **{action}** (综合得分: {score})")

    dxy_df = data.get('美元指数 (DXY)')
    if dxy_df is not None and not dxy_df.empty:
        cur_dxy = dxy_df['Close'].iloc[-1].item()
        if len(dxy_df) >= 2:
            dxy_delta = cur_dxy - dxy_df['Close'].iloc[-2].item()
        else:
             dxy_delta = 0

        with col3:
            st.metric("美元指数 DXY", f"{cur_dxy:.2f}",
                      f"{dxy_delta:.2f}", delta_color="inverse")
    else:
        with col3:
            st.metric("美元指数 DXY", "N/A", "N/A")

    # --- 2. Detailed Logic Display ---
    st.write("### 🧠 决策依据")
    for r in reasons:
        st.write(r)

    st.divider()

    # --- 3. Macro and Policy Summary (New Section) ---
    st.write("### 🏛️ 宏观政策与事件总结")

    st.info("""
    **宏观事件综合总结 (Synthesized Summary):**
    当前宏观环境主要受到美联储利率政策预期的主导。

    1.  **美联储 (Fed):** 市场普遍预计美联储已结束加息周期，焦点转向**何时开始降息**。若降息预期增强，将**压低美元和美债收益率**，对黄金形成**重大利好**。
    2.  **美国政府 (Government):** 美国政府的财政支出和不断增长的**债务规模**是长期的通胀和避险需求来源。任何关于政府停摆或财政刺激的新闻，都会在短期内**增加黄金的避险吸引力**。
    3.  **地缘政治:** 恐慌指数 (VIX) 若持续高位，表明市场避险情绪强烈，直接利好作为传统避险资产的黄金。

    *请结合上方实时技术分析得分，综合判断买卖时机。*
    """)

    st.write("#### 🔗 权威信息速览 (Direct Links)")
    st.markdown("""
    - [美联储官方网站 (FOMC声明)](https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm)
    - [美国财政部官方网站 (债务/预算)](https://home.treasury.gov/)
    - [CME FedWatch工具 (降息概率)](https://www.cmegroup.com/markets/interest-rates/cme-fedwatch-tool.html)
    """)

    st.divider()

    # --- 4. Charts and News (Existing Sections) ---
    c1, c2 = st.columns(2)

    with c1:
        st.write("### 📊 黄金 vs 美元走势 (最近1周)")

        # Prepare data for charting (max 168 hours = 7 days)
        g_data = gold_df['Close'].tail(168)
        d_data = data.get('美元指数 (DXY)', pd.DataFrame())
        d_data = d_data['Close'].tail(168)

        if not g_data.empty and not d_data.empty:
            df_chart = pd.DataFrame()
            # Normalize for comparison: (Price - Mean) / Mean
            df_chart['Gold'] = (g_data - g_data.mean()) / g_data.mean()
            df_chart['USD'] = (d_data - d_data.mean()) / d_data.mean()

            # Align indices before plotting
            df_chart = df_chart.dropna()

            st.line_chart(df_chart)
            st.caption("注：数据已归一化。通常美元跌(橙线)，黄金涨(蓝线)。")
        else:
             st.warning("图表数据不完整，无法显示黄金与美元对比走势。")


    with c2:
        st.write("### 🌍 全球宏观/政治快讯")
        if news:
            for n in news:
                st.markdown(f"**[{n['title']}]({n['link']})**")
                st.caption(f"发布时间: {n['published']}")
        else:
            st.info("暂未抓取到最新的宏观新闻。")

if __name__ == "__main__":
    main()